org.gradle.jvmargs=-Xmx3G

# Mod Info
maven_group = dev.erdragh.ponder_overrides
archives_base_name = ponder_overrides
modVersion = 0.0.2

# Development QOL
# Create supports all 3 recipe viewers: JEI, REI, and EMI. This decides which is enabled at runtime.
# set to disabled to have none of them.
recipeViewer = emi
